<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Md3.Avalonia.Gallery</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.AvaloniaEdit" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <ProjectReference Include="../../src/Md3.Avalonia/Md3.Avalonia.csproj" />
    <ProjectReference Include="../../src/Md3.Avalonia.Icons/Md3.Avalonia.Icons.csproj" />
    <ProjectReference Include="../../src/Md3.Avalonia.Ecosystem/Md3.Avalonia.Ecosystem.csproj" />
    <AvaloniaResource Include="Assets/Media/**" />
  </ItemGroup>
</Project>
